# Development environment configuration
# This file overrides default.yaml settings for local development

# Server Configuration - Development settings
server:
  port: 8080
  mode: debug  # Enable debug mode for development
  host: 0.0.0.0  # Allow connections from all interfaces

# Database Configuration - Development with optimized settings
database:
  host: localhost
  port: 3306
  user: root
  password: password
  name: sarcng_dev  # Use development database
  # Connection pool settings optimized for development
  max_open_conns: 10       # Lower connection limit for development
  max_idle_conns: 5        # Fewer idle connections
  conn_max_lifetime: 30m   # Longer lifetime for development
  conn_max_idle_time: 10m  # Longer idle time for development

# API Configuration
api:
  version: v1
  title: "SARC-NG API (Development)"
  description: "SARC Next Generation - Resource Reservation and Management API (Development Environment)"
  contact:
    name: "Development Team"
    email: "dev@example.com"

# Logging Configuration - Development
logging:
  level: debug  # More verbose logging for development
  format: text  # Human-readable format for development
  file: ""  # Log to stdout

# Authentication Configuration
auth:
  jwt:
    secret: "dev-secret-key-not-for-production"
    expiration: 168h  # 7 days for development convenience

# CORS Configuration - Development (permissive)
cors:
  allowOrigins: ["http://localhost:3000", "http://localhost:8080", "http://127.0.0.1:3000"]
  allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowHeaders: ["Origin", "Content-Type", "Accept", "Authorization"]
  exposeHeaders: ["Content-Length"]
  allowCredentials: true
  maxAge: 12h

# Swagger Configuration - Development
swagger:
  enabled: true  # Always enable in development
  path: "/swagger/*any"

# Health Check Configuration
health:
  path: "/health"

# Rate Limiting Configuration
rateLimit:
  enabled: false  # Disable rate limiting in development

# Cache Configuration
cache:
  enabled: false  # Disable caching in development for easier testing

# Development-specific settings
development:
  hotReload: true
  mockData: false
  debugRoutes: true
  verboseErrors: true

# Docker-specific overrides (when running in Docker)
docker:
  database:
    host: db  # Docker service name
    port: 3306
