name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Test
        run: |
          make setup
          make lint
          make test

  integration:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Start services
        run: |
          cd infrastructure/docker
          make dev-bg

      - name: Wait for services
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:8080/health; do sleep 2; done'

      - name: Run integration tests
        run: |
          cd infrastructure/docker
          make test-integration

      - name: Show logs on failure
        if: failure()
        run: |
          cd infrastructure/docker
          make logs

      - name: Cleanup
        if: always()
        run: |
          cd infrastructure/docker
          make clean

  build:
    runs-on: ubuntu-latest
    needs: [test, integration]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        run: make release
